# -*- coding: utf-8 -*-
from odoo import models, fields, api

class facturafiscal(models.Model):
     _name = 'facturafiscal.facturafiscal'
     _description = 'Modulo de Factura Fiscal'

     dverform = fields.Text(string="versión del formato")
     iamb = fields.Text(string="tipo de ambiente")
     itpemis = fields.Text(string="tipo de emision")
     idoc = fields.Text(string="tipo de documento")
     dnrodf = fields.Text(string="numero de factura")
     dptofacdf = fields.Text(string="punto de factura")
     dseg = fields.Char(string="seguridad")
     dfechaem = fields.Text(string="fecha de emision")
     inatop = fields.Text(string="naturaleza de la operacion")
     itipoop = fields.Text(string="tipo de operacion")
     idest = fields.Text(string="destino")
     iformcafe = fields.Text(string="Formato de generación del CAFE")
     ientcafe = fields.Text(string="Manera de entrega del CAFE al receptor")
     denvfe = fields.Text(string="envio de factura")
     iprogen = fields.Text(string="proceso de generacion")
     itipotranventa = fields.Text(string="tipo de transaccion de venta")
     dtiporuc = fields.Text(string="tipo de contribuyente")
     druc = fields.Text(string="ruc")
     ddv = fields.Text(string="digito verificador")
     dnombem = fields.Text(string="nombre del emisor")
     dsucem = fields.Text(string="sucursal del emisor")
     dcoordem = fields.Text(string="coordenadas del emisor")
     ddirecem = fields.Text(string="direccion del emisor")
     dcodubi = fields.Text(string="codigo de ubicacion")
     dcorreg = fields.Text(string="corregimiento")
     ddist = fields.Text(string="distrito")
     dprov = fields.Char(string="provincia")
     dtfnem = fields.Text(string="telefono del emisor")
     dcorelectemi = fields.Text(string="correo electronico del emisor")
     itiporec = fields.Text(string="tipo de receptor")
     dtiporucrec = fields.Text(string="tipo de ruc del receptor")
     drucrec = fields.Text(string="ruc del receptor")
     ddvrec = fields.Text(string="digito verificador del receptor")
     dnombrec = fields.Text(string="nombre del receptor")
     ddirecrec = fields.Text(string="direccion del receptor")
     dcodubirec = fields.Text(string="codigo de ubicacion del receptor")
     dcorregrec = fields.Text(string="corregimiento del receptor")
     ddistrec = fields.Text(string="distrito del receptor")
     dprovrec = fields.Text(string="provincia del receptor")
     dpaisrec = fields.Text(string="pais del receptor")
     dsecitem = fields.Text(string="numero secuencial del item")
     ddescprod = fields.Text(string="descripcion del producto")
     dcodprod = fields.Text(string="codigo interno del item")
     dcantcodint = fields.Text(string="cantidad del producto o servicio, en la unidad de medida del codigo interno")
     dcodcpbsabr = fields.Text(string="codigo del Ítem en la Codificación Panameña de Bienes y Servicios Abreviada")
     dprunit = fields.Text(string="precio unitario del producto o servicio")
     dprunitdesc = fields.Text(string="descuento del precio del item")
     dpritem = fields.Text(string="precio total del producto o servicio")
     dvaltotitem = fields.Text(string="monto del itbms del item")
     dtasaitbms = fields.Text(string="tasa de itbms aplicable al item")  
     dvalitbms = fields.Text(string="valor de itbms del item")
     estadofactura = fields.Text(string="estado de la factura")
     LisProduct = fields.Json(string="Lista de Productos")